en:
- section: Developer
  items:
    - question: Writing Smart Contracts on Edgeware
      answer: |
        http://tiny.cc/ink-workshop

    - question: Run an Edgeware Node
      answer: |
        If you're interested in running a node, this is the main repository for [Edgeware](https://github.com/hicommonwealth/edgeware-node)

    - question: Edgeware Documentation (WIP)
      answer: |
        [https://edgeware.gitbook.io/doc-edgewa-re/](https://edgeware.gitbook.io/doc-edgewa-re/)

    - question: Edgeware Telemetry
      answer: |
        Check on the status of the network, monitor number of nodes and more.
        
        [https://telemetry.polkadot.io/#/Edgeware Testnet V0.2.0](https://telemetry.polkadot.io/#/Edgeware%20Testnet%20V0.2.0)

    - question: Edgeware Faucet 
      answer: |
        [https://faucets.blockxlabs.com/](https://faucets.blockxlabs.com/)

    - question: What is Substrate?
      answer: |
        Substrate is the underlying technology that Edgeware is built on. Substrate is built by Parity. 
        Documentation can be found: 
            https://docs.substrate.dev/
        Start your own chain:
            https://github.com/paritytech/substrate
        Join the chat:
            https://riot.im/app/#/room/#substrate-technical:matrix.org

    - question: What is Polkadot?
      answer: |
        [https://github.com/w3f/polkadot-wiki/](https://github.com/w3f/polkadot-wiki/)
        [https://wiki.polkadot.network/en/latest/](https://wiki.polkadot.network/en/latest/)

## Chinese
cn:
- section: Developer
  items:
    - question: Writing Smart Contracts on Edgeware
      answer: |
        [http://tiny.cc/ink-workshop](http://tiny.cc/ink-workshop)
        [https://github.com/shawntabrizi/substrate-package/tree/contract](https://github.com/shawntabrizi/substrate-package/tree/contract)
        [https://shawntabrizi.com/substrate-contracts-workshop/#/](https://shawntabrizi.com/substrate-contracts-workshop/#/)

    - question: Run an Edgeware Node
      answer: |
        If you're interested in running a node, this is the main repository for [Edgeware](https://github.com/hicommonwealth/edgeware-node)

    - question: Edgeware Documentation (WIP)
      answer: |
        [https://edgeware.gitbook.io/doc-edgewa-re/](https://edgeware.gitbook.io/doc-edgewa-re/)

    - question: Edgeware Telemetry
      answer: |
        Check on the status of the network, monitor number of nodes and more.
        
        [https://telemetry.polkadot.io/#/Edgeware Testnet V0.2.0](https://telemetry.polkadot.io/#/Edgeware%20Testnet%20V0.2.0)

    - question: Edgeware Faucet 
      answer: |
        [https://faucets.blockxlabs.com/](https://faucets.blockxlabs.com/)

    - question: What is Substrate?
      answer: |
        Substrate is the underlying technology that Edgeware is built on. Substrate is built by Parity. 
        Documentation can be found: 
            https://docs.substrate.dev/
        Start your own chain:
            https://github.com/paritytech/substrate
        Join the chat:
            https://riot.im/app/#/room/#substrate-technical:matrix.org

    - question: What is Polkadot?
      answer: |
        [https://github.com/w3f/polkadot-wiki/](https://github.com/w3f/polkadot-wiki/)
        [https://wiki.polkadot.network/en/latest/](https://wiki.polkadot.network/en/latest/)



## Japanese
jp:
- section: Developer
  items:
    - question: Writing Smart Contracts on Edgeware
      answer: |
        [http://tiny.cc/ink-workshop](http://tiny.cc/ink-workshop)
        [https://github.com/shawntabrizi/substrate-package/tree/contract](https://github.com/shawntabrizi/substrate-package/tree/contract)
        [https://shawntabrizi.com/substrate-contracts-workshop/#/](https://shawntabrizi.com/substrate-contracts-workshop/#/)

    - question: Run an Edgeware Node
      answer: |
        If you're interested in running a node, this is the main repository for [Edgeware](https://github.com/hicommonwealth/edgeware-node)

    - question: Edgeware Documentation (WIP)
      answer: |
        [https://edgeware.gitbook.io/doc-edgewa-re/](https://edgeware.gitbook.io/doc-edgewa-re/)

    - question: Edgeware Telemetry
      answer: |
        Check on the status of the network, monitor number of nodes and more.
        
        [https://telemetry.polkadot.io/#/Edgeware Testnet V0.2.0](https://telemetry.polkadot.io/#/Edgeware%20Testnet%20V0.2.0)

    - question: Edgeware Faucet 
      answer: |
        [https://faucets.blockxlabs.com/](https://faucets.blockxlabs.com/)

    - question: What is Substrate?
      answer: |
        Substrate is the underlying technology that Edgeware is built on. Substrate is built by Parity. 
        Documentation can be found: 
            https://docs.substrate.dev/
        Start your own chain:
            https://github.com/paritytech/substrate
        Join the chat:
            https://riot.im/app/#/room/#substrate-technical:matrix.org

    - question: What is Polkadot?
      answer: |
        [https://github.com/w3f/polkadot-wiki/](https://github.com/w3f/polkadot-wiki/)
        [https://wiki.polkadot.network/en/latest/](https://wiki.polkadot.network/en/latest/)

## Cantonese
canto:
- section: Developer
  items:
    - question: Writing Smart Contracts on Edgeware
      answer: |
        [http://tiny.cc/ink-workshop](http://tiny.cc/ink-workshop)
        [https://github.com/shawntabrizi/substrate-package/tree/contract](https://github.com/shawntabrizi/substrate-package/tree/contract)
        [https://shawntabrizi.com/substrate-contracts-workshop/#/](https://shawntabrizi.com/substrate-contracts-workshop/#/)

    - question: Run an Edgeware Node
      answer: |
        If you're interested in running a node, this is the main repository for [Edgeware](https://github.com/hicommonwealth/edgeware-node)

    - question: Edgeware Documentation (WIP)
      answer: |
        [https://edgeware.gitbook.io/doc-edgewa-re/](https://edgeware.gitbook.io/doc-edgewa-re/)

    - question: Edgeware Telemetry
      answer: |
        Check on the status of the network, monitor number of nodes and more.
        
        [https://telemetry.polkadot.io/#/Edgeware Testnet V0.2.0](https://telemetry.polkadot.io/#/Edgeware%20Testnet%20V0.2.0)

    - question: Edgeware Faucet 
      answer: |
        [https://faucets.blockxlabs.com/](https://faucets.blockxlabs.com/)

    - question: What is Substrate?
      answer: |
        Substrate is the underlying technology that Edgeware is built on. Substrate is built by Parity. 
        Documentation can be found: 
            https://docs.substrate.dev/
        Start your own chain:
            https://github.com/paritytech/substrate
        Join the chat:
            https://riot.im/app/#/room/#substrate-technical:matrix.org

    - question: What is Polkadot?
      answer: |
        [https://github.com/w3f/polkadot-wiki/](https://github.com/w3f/polkadot-wiki/)
        [https://wiki.polkadot.network/en/latest/](https://wiki.polkadot.network/en/latest/)

## Korean
ko:
- section: Developer
  items:
    - question: Writing Smart Contracts on Edgeware
      answer: |
        [http://tiny.cc/ink-workshop](http://tiny.cc/ink-workshop)
        [https://github.com/shawntabrizi/substrate-package/tree/contract](https://github.com/shawntabrizi/substrate-package/tree/contract)
        [https://shawntabrizi.com/substrate-contracts-workshop/#/](https://shawntabrizi.com/substrate-contracts-workshop/#/)

    - question: Run an Edgeware Node
      answer: |
        If you're interested in running a node, this is the main repository for [Edgeware](https://github.com/hicommonwealth/edgeware-node)

    - question: Edgeware Documentation (WIP)
      answer: |
        [https://edgeware.gitbook.io/doc-edgewa-re/](https://edgeware.gitbook.io/doc-edgewa-re/)

    - question: Edgeware Telemetry
      answer: |
        Check on the status of the network, monitor number of nodes and more.
        
        [https://telemetry.polkadot.io/#/Edgeware Testnet V0.2.0](https://telemetry.polkadot.io/#/Edgeware%20Testnet%20V0.2.0)

    - question: Edgeware Faucet 
      answer: |
        [https://faucets.blockxlabs.com/](https://faucets.blockxlabs.com/)

    - question: What is Substrate?
      answer: |
        Substrate is the underlying technology that Edgeware is built on. Substrate is built by Parity. 
        Documentation can be found: 
            https://docs.substrate.dev/
        Start your own chain:
            https://github.com/paritytech/substrate
        Join the chat:
            https://riot.im/app/#/room/#substrate-technical:matrix.org

    - question: What is Polkadot?
      answer: |
        [https://github.com/w3f/polkadot-wiki/](https://github.com/w3f/polkadot-wiki/)
        [https://wiki.polkadot.network/en/latest/](https://wiki.polkadot.network/en/latest/)

debug:
- section: Debug
  items:
    - question: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
      answer: |
        Sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
        aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia
        deserunt mollit anim id est laborum.
